# Generated by Django 4.0.2 on 2022-09-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortedUrl',
            new_name='Url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='key',
            new_name='short_url',
        ),
    ]
